#!/usr/bin/env python3
"""VaultUploader entry point."""

import argparse
import sys

from vaultuploader import cli
from vaultuploader.client import server


class VaultUploaderClient(cli.Application):

    """VaultUploaderClient command line application."""

    commands = [
        (server.Server, "commands"),
    ]

    def setup(self):
        """Extend the parser configuration in order to expose all
        the received commands.
        """
        self._parser = argparse.ArgumentParser()
        commands = self._parser.add_subparsers(
            title="[commands]", dest="command")

        self._register_parser("commands", commands)


def main():
    """Run the VaultUploader command line application."""
    vaultuploader = VaultUploaderClient(sys.argv[1:])
    vaultuploader.run()


if __name__ == "__main__":
    main()